# Generated by Django 3.1.3 on 2020-11-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_userbookrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookrelation',
            name='in_bookmarks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userbookrelation',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userbookrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ok'), (2, 'Fine'), (3, 'Good'), (4, 'Amazing'), (5, 'Incredible')], default=1),
            preserve_default=False,
        ),
    ]
