# Generated by Django 3.1.3 on 2020-11-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20201115_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='raiting',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3, null=True),
        ),
    ]
